export type AnimalSpecies = "Dog" | "Cat" | "Bird";
export type AnimalSize = "Small" | "Medium" | "Large";
export type AnimalGender = "Female" | "Male";

export type AdoptAnimal = {
  slug: string;
  name: string;
  breed: string;
  age: string;
  ageYears: number;
  species: AnimalSpecies;
  size: AnimalSize;
  gender: AnimalGender;
  image: string;
  status: string;
  pair?: string;
  city: string;
  temperament: string[];
  vaccinated: boolean;
  neutered: boolean;
  goodWith: string;
  profileSummary: string;
  rescueStory: string;
};

export const adoptAnimals: AdoptAnimal[] = [
  {
    slug: "murphy",
    name: "Murphy",
    breed: "Golden Retriever",
    age: "2 Years",
    ageYears: 2,
    species: "Dog",
    size: "Large",
    gender: "Male",
    status: "Newly Rescued",
    image: "/images/unsplash/photo-1543466835-00a7907e9de1.jpg",
    city: "Bengaluru",
    temperament: ["Friendly", "Playful", "Gentle"],
    vaccinated: true,
    neutered: true,
    goodWith: "Children and other dogs",
    profileSummary: "An affectionate retriever who loves fetch and evening walks.",
    rescueStory: "Murphy was found near a market road with a leg injury. After treatment and rehab, he is now healthy and eager to join a loving family.",
  },
  {
    slug: "luna",
    name: "Luna",
    breed: "Domestic Shorthair",
    age: "4 Years",
    ageYears: 4,
    species: "Cat",
    size: "Small",
    gender: "Female",
    status: "Foster Home",
    image: "/images/unsplash/photo-1517849845537-4d257902454a.jpg",
    city: "Chennai",
    temperament: ["Calm", "Litter Trained", "Affectionate"],
    vaccinated: true,
    neutered: true,
    goodWith: "Quiet homes and older kids",
    profileSummary: "A calm indoor cat who enjoys window naps and soft toys.",
    rescueStory: "Luna was surrendered when her previous owner moved overseas. She adjusted quickly in foster care and now seeks a stable forever home.",
  },
  {
    slug: "scout-jem",
    name: "Scout & Jem",
    breed: "Border Collie Mix",
    age: "6 Months",
    ageYears: 0.5,
    species: "Dog",
    size: "Medium",
    gender: "Male",
    status: "Active",
    pair: "Bonded Pair",
    image: "/images/unsplash/photo-1601758228041-f3b2795255f1.jpg",
    city: "Pune",
    temperament: ["Energetic", "Smart", "Trainable"],
    vaccinated: true,
    neutered: false,
    goodWith: "Active families",
    profileSummary: "Young bonded brothers with endless energy and curiosity.",
    rescueStory: "The brothers were rescued from a construction site and raised together in our center. They are deeply bonded and should be adopted together.",
  },
  {
    slug: "balthazar",
    name: "Balthazar",
    breed: "Great Dane",
    age: "5 Years",
    ageYears: 5,
    species: "Dog",
    size: "Large",
    gender: "Male",
    status: "Ready",
    image: "/images/unsplash/photo-1548199973-03cce0bbc87b.jpg",
    city: "Hyderabad",
    temperament: ["Calm", "Loyal", "Protective"],
    vaccinated: true,
    neutered: true,
    goodWith: "Experienced large-dog adopters",
    profileSummary: "A gentle giant who enjoys relaxed routines and space.",
    rescueStory: "Balthazar was rescued after being abandoned at a highway stop. He has completed obedience training and is now adoption-ready.",
  },
  {
    slug: "rio",
    name: "Rio",
    breed: "Macaw",
    age: "12 Years",
    ageYears: 12,
    species: "Bird",
    size: "Large",
    gender: "Male",
    status: "Expert Required",
    image: "/images/unsplash/photo-1530281700549-e82e7bf110d6.jpg",
    city: "Kochi",
    temperament: ["Vocal", "Intelligent", "Curious"],
    vaccinated: true,
    neutered: false,
    goodWith: "Bird-experienced homes",
    profileSummary: "A stunning macaw who needs enrichment and social attention.",
    rescueStory: "Rio came from an illegal private sale and required careful rehabilitation. He now thrives with daily interaction and structured enrichment.",
  },
  {
    slug: "oliver",
    name: "Oliver",
    breed: "Tabby Mix",
    age: "3 Months",
    ageYears: 0.25,
    species: "Cat",
    size: "Small",
    gender: "Male",
    status: "Newly Rescued",
    image: "/images/unsplash/photo-1552053831-71594a27632d.jpg",
    city: "Bengaluru",
    temperament: ["Curious", "Playful", "Social"],
    vaccinated: true,
    neutered: false,
    goodWith: "Families and friendly pets",
    profileSummary: "A lively kitten who loves climbing and chasing toys.",
    rescueStory: "Oliver was found alone during monsoon season and bottle-fed by our neonatal team. He is now healthy and fully weaned.",
  },
  {
    slug: "hazel",
    name: "Hazel",
    breed: "Labrador Mix",
    age: "1 Year",
    ageYears: 1,
    species: "Dog",
    size: "Large",
    gender: "Female",
    status: "Ready",
    image: "/images/unsplash/photo-1507146426996-ef05306b995a.jpg",
    city: "Mysuru",
    temperament: ["Obedient", "Friendly", "Food Motivated"],
    vaccinated: true,
    neutered: true,
    goodWith: "Families with kids",
    profileSummary: "A sweet lab mix who responds well to commands.",
    rescueStory: "Hazel was brought in after a minor road accident. She recovered quickly and now enjoys group play sessions every day.",
  },
  {
    slug: "milo",
    name: "Milo",
    breed: "Indie Dog",
    age: "2 Years",
    ageYears: 2,
    species: "Dog",
    size: "Medium",
    gender: "Male",
    status: "Foster Home",
    image: "/images/unsplash/photo-1548199973-03cce0bbc87b.jpg",
    city: "Mumbai",
    temperament: ["Alert", "Loving", "Adaptable"],
    vaccinated: true,
    neutered: true,
    goodWith: "Apartment homes",
    profileSummary: "A smart indie dog who settles well indoors.",
    rescueStory: "Milo was rescued during a storm and treated for skin infection. He has fully recovered and thrives in foster routines.",
  },
  {
    slug: "pepper",
    name: "Pepper",
    breed: "Domestic Shorthair",
    age: "8 Months",
    ageYears: 0.67,
    species: "Cat",
    size: "Small",
    gender: "Female",
    status: "Newly Rescued",
    image: "/images/unsplash/photo-1519052537078-e6302a4968d4.jpg",
    city: "Coimbatore",
    temperament: ["Gentle", "Quiet", "Affectionate"],
    vaccinated: true,
    neutered: false,
    goodWith: "Calm households",
    profileSummary: "A soft-natured cat who likes calm corners and cuddles.",
    rescueStory: "Pepper was rescued from a warehouse colony during a relocation drive. She is now healthy and confidently socializing.",
  },
  {
    slug: "koda",
    name: "Koda",
    breed: "Husky Mix",
    age: "3 Years",
    ageYears: 3,
    species: "Dog",
    size: "Large",
    gender: "Male",
    status: "Active",
    image: "/images/unsplash/photo-1560250097-0b93528c311a.jpg",
    city: "Delhi",
    temperament: ["Athletic", "Independent", "Loyal"],
    vaccinated: true,
    neutered: true,
    goodWith: "Active adopters",
    profileSummary: "A high-energy companion who loves runs and puzzles.",
    rescueStory: "Koda was relinquished due to relocation and high activity needs. He now follows a structured enrichment and training plan.",
  },
  {
    slug: "nori",
    name: "Nori",
    breed: "Parakeet",
    age: "2 Years",
    ageYears: 2,
    species: "Bird",
    size: "Small",
    gender: "Female",
    status: "Expert Required",
    image: "/images/unsplash/photo-1623387641168-d9803ddd3f35.jpg",
    city: "Goa",
    temperament: ["Social", "Chirpy", "Active"],
    vaccinated: true,
    neutered: false,
    goodWith: "Homes with daily interaction",
    profileSummary: "A bright parakeet who bonds through routine care.",
    rescueStory: "Nori was confiscated from cramped housing and rehabilitated with flight exercise. She now needs a spacious, stimulating environment.",
  },
  {
    slug: "coco",
    name: "Coco",
    breed: "Calico Cat",
    age: "1 Year",
    ageYears: 1,
    species: "Cat",
    size: "Small",
    gender: "Female",
    status: "Ready",
    image: "/images/unsplash/photo-1542204625-de293a38bda2.jpg",
    city: "Nagpur",
    temperament: ["Playful", "Confident", "Curious"],
    vaccinated: true,
    neutered: true,
    goodWith: "Families and calm dogs",
    profileSummary: "A confident calico with a playful personality.",
    rescueStory: "Coco was rescued as a kitten with mild malnutrition. She has regained full health and enjoys interactive toys.",
  },
  {
    slug: "bruno",
    name: "Bruno",
    breed: "Indie Dog",
    age: "4 Years",
    ageYears: 4,
    species: "Dog",
    size: "Medium",
    gender: "Male",
    status: "Ready",
    image: "/images/unsplash/photo-1548199973-03cce0bbc87b.jpg",
    city: "Pune",
    temperament: ["Calm", "Friendly", "Leash Trained"],
    vaccinated: true,
    neutered: true,
    goodWith: "First-time adopters",
    profileSummary: "A calm street-survivor who now loves gentle routines.",
    rescueStory: "Bruno recovered from dehydration and now volunteers often use him in socialization walks because of his stable temperament.",
  },
  {
    slug: "zara",
    name: "Zara",
    breed: "German Shepherd Mix",
    age: "2 Years",
    ageYears: 2,
    species: "Dog",
    size: "Large",
    gender: "Female",
    status: "Active",
    image: "/images/unsplash/photo-1507146426996-ef05306b995a.jpg",
    city: "Bengaluru",
    temperament: ["Alert", "Trainable", "Protective"],
    vaccinated: true,
    neutered: true,
    goodWith: "Experienced adopters",
    profileSummary: "A sharp and loyal companion with strong recall skills.",
    rescueStory: "Zara was surrendered due to housing restrictions. She has completed advanced obedience and enjoys agility tasks.",
  },
  {
    slug: "toffee",
    name: "Toffee",
    breed: "Beagle Mix",
    age: "1.5 Years",
    ageYears: 1.5,
    species: "Dog",
    size: "Medium",
    gender: "Male",
    status: "Foster Home",
    image: "/images/unsplash/photo-1560250097-0b93528c311a.jpg",
    city: "Chennai",
    temperament: ["Cheerful", "Food Motivated", "Social"],
    vaccinated: true,
    neutered: true,
    goodWith: "Kids and active homes",
    profileSummary: "A cheerful beagle mix who loves scent games.",
    rescueStory: "Toffee was rescued from a breeder closure and gradually learned home routines in foster care.",
  },
  {
    slug: "simba",
    name: "Simba",
    breed: "Indie Dog",
    age: "7 Months",
    ageYears: 0.58,
    species: "Dog",
    size: "Medium",
    gender: "Male",
    status: "Newly Rescued",
    image: "/images/unsplash/photo-1543466835-00a7907e9de1.jpg",
    city: "Kolkata",
    temperament: ["Curious", "Playful", "Learning Fast"],
    vaccinated: true,
    neutered: false,
    goodWith: "Families with time for training",
    profileSummary: "A young pup with lots of potential and warmth.",
    rescueStory: "Simba was rescued from a drainage canal and has made a full recovery under neonatal and behavioral care.",
  },
  {
    slug: "daisy",
    name: "Daisy",
    breed: "Cocker Spaniel Mix",
    age: "3 Years",
    ageYears: 3,
    species: "Dog",
    size: "Medium",
    gender: "Female",
    status: "Ready",
    image: "/images/unsplash/photo-1507146426996-ef05306b995a.jpg",
    city: "Jaipur",
    temperament: ["Affectionate", "Gentle", "Quiet"],
    vaccinated: true,
    neutered: true,
    goodWith: "Indoor homes",
    profileSummary: "A gentle spaniel mix who bonds deeply with her people.",
    rescueStory: "Daisy was surrendered after her owner developed medical issues. She is healthy and emotionally steady.",
  },
  {
    slug: "leo",
    name: "Leo",
    breed: "Labrador Retriever",
    age: "6 Years",
    ageYears: 6,
    species: "Dog",
    size: "Large",
    gender: "Male",
    status: "Ready",
    image: "/images/unsplash/photo-1548199973-03cce0bbc87b.jpg",
    city: "Ahmedabad",
    temperament: ["Mature", "Loyal", "Calm"],
    vaccinated: true,
    neutered: true,
    goodWith: "Families wanting a calm companion",
    profileSummary: "A mature lab with excellent home manners.",
    rescueStory: "Leo was found wandering with an old collar tag. After recovery and assessment, he proved to be calm and people-focused.",
  },
  {
    slug: "whiskers",
    name: "Whiskers",
    breed: "Persian Mix",
    age: "2 Years",
    ageYears: 2,
    species: "Cat",
    size: "Small",
    gender: "Male",
    status: "Ready",
    image: "/images/unsplash/photo-1542204625-de293a38bda2.jpg",
    city: "Mumbai",
    temperament: ["Calm", "Indoor", "Grooming Friendly"],
    vaccinated: true,
    neutered: true,
    goodWith: "Quiet apartments",
    profileSummary: "A fluffy companion who enjoys gentle attention.",
    rescueStory: "Whiskers came from an overcrowded apartment surrender and now enjoys consistent grooming and indoor play.",
  },
  {
    slug: "mittens",
    name: "Mittens",
    breed: "Domestic Longhair",
    age: "5 Months",
    ageYears: 0.42,
    species: "Cat",
    size: "Small",
    gender: "Female",
    status: "Foster Home",
    image: "/images/unsplash/photo-1552053831-71594a27632d.jpg",
    city: "Pune",
    temperament: ["Playful", "Social", "Litter Trained"],
    vaccinated: true,
    neutered: false,
    goodWith: "Families with supervised kids",
    profileSummary: "A lively kitten with bright curiosity and confidence.",
    rescueStory: "Mittens was rescued from a parking basement and moved to foster care where she quickly adapted to home life.",
  },
  {
    slug: "mocha",
    name: "Mocha",
    breed: "Siamese Mix",
    age: "1.5 Years",
    ageYears: 1.5,
    species: "Cat",
    size: "Small",
    gender: "Female",
    status: "Active",
    image: "/images/unsplash/photo-1519052537078-e6302a4968d4.jpg",
    city: "Bengaluru",
    temperament: ["Vocal", "Smart", "Affectionate"],
    vaccinated: true,
    neutered: true,
    goodWith: "Homes that can provide attention",
    profileSummary: "An expressive cat who thrives on interaction.",
    rescueStory: "Mocha was rescued from a closed pet shop and has blossomed with regular play and social handling.",
  },
  {
    slug: "cleo",
    name: "Cleo",
    breed: "Indie Cat",
    age: "3 Years",
    ageYears: 3,
    species: "Cat",
    size: "Small",
    gender: "Female",
    status: "Ready",
    image: "/images/unsplash/photo-1542204625-de293a38bda2.jpg",
    city: "Hyderabad",
    temperament: ["Independent", "Gentle", "Observant"],
    vaccinated: true,
    neutered: true,
    goodWith: "Adults and calm homes",
    profileSummary: "An independent but affectionate cat with soft manners.",
    rescueStory: "Cleo was rescued from a warehouse colony and now enjoys stable indoor routines with occasional play bursts.",
  },
  {
    slug: "figaro",
    name: "Figaro",
    breed: "Tabby",
    age: "4 Years",
    ageYears: 4,
    species: "Cat",
    size: "Small",
    gender: "Male",
    status: "Foster Home",
    image: "/images/unsplash/photo-1517849845537-4d257902454a.jpg",
    city: "Delhi",
    temperament: ["Easygoing", "Friendly", "Indoor"],
    vaccinated: true,
    neutered: true,
    goodWith: "Families and senior adopters",
    profileSummary: "A balanced tabby who adjusts well to new spaces.",
    rescueStory: "Figaro was surrendered when his family relocated abroad. He has been thriving in foster care and is now ready for adoption.",
  },
  {
    slug: "sky",
    name: "Sky",
    breed: "Cockatiel",
    age: "1 Year",
    ageYears: 1,
    species: "Bird",
    size: "Small",
    gender: "Female",
    status: "Ready",
    image: "/images/unsplash/photo-1623387641168-d9803ddd3f35.jpg",
    city: "Chandigarh",
    temperament: ["Curious", "Whistles", "Hand-Tame"],
    vaccinated: true,
    neutered: false,
    goodWith: "Homes with bird-safe spaces",
    profileSummary: "A bright cockatiel who enjoys gentle training.",
    rescueStory: "Sky was rescued from unsafe caging conditions and regained full feather health with proper nutrition and flight time.",
  },
  {
    slug: "kiwi",
    name: "Kiwi",
    breed: "Lovebird",
    age: "9 Months",
    ageYears: 0.75,
    species: "Bird",
    size: "Small",
    gender: "Male",
    status: "Active",
    image: "/images/unsplash/photo-1530281700549-e82e7bf110d6.jpg",
    city: "Kochi",
    temperament: ["Social", "Energetic", "Vocal"],
    vaccinated: true,
    neutered: false,
    goodWith: "Bird companionship homes",
    profileSummary: "A colorful lovebird with playful social energy.",
    rescueStory: "Kiwi was rescued after an accidental release and treated for mild wing strain. He now flies confidently and seeks a safe home.",
  },
  {
    slug: "amber",
    name: "Amber",
    breed: "Indian Ringneck",
    age: "3 Years",
    ageYears: 3,
    species: "Bird",
    size: "Medium",
    gender: "Female",
    status: "Expert Required",
    image: "/images/unsplash/photo-1623387641168-d9803ddd3f35.jpg",
    city: "Pune",
    temperament: ["Intelligent", "Reserved", "Trainable"],
    vaccinated: true,
    neutered: false,
    goodWith: "Experienced bird handlers",
    profileSummary: "A highly intelligent ringneck that needs patient bonding.",
    rescueStory: "Amber was rescued from a neglect case and underwent behavioral rehabilitation. She now accepts structured social sessions.",
  },
  {
    slug: "pico",
    name: "Pico",
    breed: "Budgerigar",
    age: "2 Years",
    ageYears: 2,
    species: "Bird",
    size: "Small",
    gender: "Male",
    status: "Ready",
    image: "/images/unsplash/photo-1530281700549-e82e7bf110d6.jpg",
    city: "Vizag",
    temperament: ["Chirpy", "Interactive", "Gentle"],
    vaccinated: true,
    neutered: false,
    goodWith: "Companion bird homes",
    profileSummary: "A lively budgie that enjoys human interaction.",
    rescueStory: "Pico was surrendered when his owner moved. He remains healthy and active with daily enrichment sessions.",
  },
  {
    slug: "mango",
    name: "Mango",
    breed: "Sun Conure",
    age: "4 Years",
    ageYears: 4,
    species: "Bird",
    size: "Medium",
    gender: "Female",
    status: "Foster Home",
    image: "/images/unsplash/photo-1530281700549-e82e7bf110d6.jpg",
    city: "Mumbai",
    temperament: ["Vocal", "Affectionate", "High-Energy"],
    vaccinated: true,
    neutered: false,
    goodWith: "Experienced adopters",
    profileSummary: "A social conure who loves interactive toys and music.",
    rescueStory: "Mango was rehabilitated after feather damage and now follows a healthy routine with supervised flight and play.",
  },
  {
    slug: "max",
    name: "Max",
    breed: "Rottweiler Mix",
    age: "4 Years",
    ageYears: 4,
    species: "Dog",
    size: "Large",
    gender: "Male",
    status: "Ready",
    image: "/images/unsplash/photo-1560250097-0b93528c311a.jpg",
    city: "Bhopal",
    temperament: ["Loyal", "Strong", "Well-Trained"],
    vaccinated: true,
    neutered: true,
    goodWith: "Experienced large-dog homes",
    profileSummary: "A disciplined companion with strong loyalty.",
    rescueStory: "Max was surrendered for financial reasons and was already obedience-trained. He is healthy and adoption-ready.",
  },
  {
    slug: "ginger",
    name: "Ginger",
    breed: "Orange Tabby",
    age: "2 Years",
    ageYears: 2,
    species: "Cat",
    size: "Small",
    gender: "Female",
    status: "Ready",
    image: "/images/unsplash/photo-1519052537078-e6302a4968d4.jpg",
    city: "Lucknow",
    temperament: ["Friendly", "Playful", "Food Motivated"],
    vaccinated: true,
    neutered: true,
    goodWith: "Kids and adults",
    profileSummary: "A sunny personality with a love for toy mice.",
    rescueStory: "Ginger was rescued during a colony sterilization drive and quickly became a favorite in foster care.",
  },
  {
    slug: "pluto",
    name: "Pluto",
    breed: "Indie Dog",
    age: "5 Years",
    ageYears: 5,
    species: "Dog",
    size: "Medium",
    gender: "Male",
    status: "Foster Home",
    image: "/images/unsplash/photo-1543466835-00a7907e9de1.jpg",
    city: "Surat",
    temperament: ["Steady", "Gentle", "Patient"],
    vaccinated: true,
    neutered: true,
    goodWith: "Calm homes",
    profileSummary: "A gentle adult dog with excellent house manners.",
    rescueStory: "Pluto was rescued with a minor paw injury and has recovered fully. He adapts well to quiet homes.",
  },
  {
    slug: "ivy",
    name: "Ivy",
    breed: "Domestic Shorthair",
    age: "1 Year",
    ageYears: 1,
    species: "Cat",
    size: "Small",
    gender: "Female",
    status: "Active",
    image: "/images/unsplash/photo-1552053831-71594a27632d.jpg",
    city: "Thiruvananthapuram",
    temperament: ["Curious", "Climber", "Friendly"],
    vaccinated: true,
    neutered: true,
    goodWith: "Homes with enrichment",
    profileSummary: "A curious young cat who enjoys climbing trees and shelves.",
    rescueStory: "Ivy was rescued from a residential parking lot and has become confident through gradual socialization.",
  },
  {
    slug: "rocky",
    name: "Rocky",
    breed: "Boxer Mix",
    age: "2 Years",
    ageYears: 2,
    species: "Dog",
    size: "Large",
    gender: "Male",
    status: "Ready",
    image: "/images/unsplash/photo-1548199973-03cce0bbc87b.jpg",
    city: "Noida",
    temperament: ["Energetic", "Friendly", "Loyal"],
    vaccinated: true,
    neutered: true,
    goodWith: "Active families",
    profileSummary: "A playful boxer mix with great social confidence.",
    rescueStory: "Rocky was found near an industrial area and recovered from mild malnutrition. He now enjoys agility games.",
  },
  {
    slug: "pearl",
    name: "Pearl",
    breed: "Cockatiel",
    age: "2 Years",
    ageYears: 2,
    species: "Bird",
    size: "Small",
    gender: "Female",
    status: "Ready",
    image: "/images/unsplash/photo-1623387641168-d9803ddd3f35.jpg",
    city: "Kolkata",
    temperament: ["Gentle", "Hand-Tame", "Quiet"],
    vaccinated: true,
    neutered: false,
    goodWith: "Quiet bird-friendly homes",
    profileSummary: "A calm cockatiel that responds to patient handling.",
    rescueStory: "Pearl was surrendered from a household unable to continue care. She is healthy and settled in foster care.",
  },
  {
    slug: "tango",
    name: "Tango",
    breed: "Lovebird",
    age: "1 Year",
    ageYears: 1,
    species: "Bird",
    size: "Small",
    gender: "Male",
    status: "Active",
    image: "/images/unsplash/photo-1530281700549-e82e7bf110d6.jpg",
    city: "Indore",
    temperament: ["Playful", "Social", "Vocal"],
    vaccinated: true,
    neutered: false,
    goodWith: "Homes with interaction time",
    profileSummary: "A social lovebird with strong pair-bonding behavior.",
    rescueStory: "Tango came from an overcrowded aviary and has been rehabilitated with enrichment and monitored socialization.",
  },
];

export function findAnimalBySlug(slug: string) {
  return adoptAnimals.find((animal) => animal.slug === slug);
}
